### ISSUE TITLE
ForceDiagram.ordered_edges() ignores FormDiagram's edges' 'is_true' attributes

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#13]
ForceDiagram.ordered_edges() ignores FormDiagram's edges' 'is_true' attributes 

_Suggest changing_
edges     = [index_uv[index] for index in range(self.number_of_edges())]
_to_
n_form_true_edges = len(list(form.edges_where({'is_edge': True})))
edges     = [index_uv[index] for index in range(n_form_true_edges)]

**Comment by brgcode** [comment]
as far as i can tell the code is correct. it is not the number of edges in the form diagram that matters in this context but rather the number of edges in the force diagram, and this is number can be counted correctly with `self.number_of_edges()`.

the `is_true` flag is used correctly in the `uv_index` function to enumerate the true edges of the form diagram.

can you give an example of where this doesn't work as expected?

**Comment by brgcode** [comment]
can i close this?
