### ISSUE TITLE
diagram.draw()  doesn't work when updating settings 

### ISSUE THREAD

**Issue by cristianjcb** [BlockResearchGroup/compas_tna#17]
Message: 'FormArtist' object has no attribute 'datastructure'.

settings = {
    'show.forces'    : True,
    'show.reactions' : True,
    'scale.forces'   : 0.02,
    'scale.reactions': 1.0
}

form.draw(layer='TNA::Vault', clear_layer=True, settings=settings)

**Comment by brgcode** [comment]
check latest commit

**Comment by brgcode** [comment]
can i close this?

**Comment by cristianjcb** [comment]
Yeap!!

—
*Cristián Calvo Barentin*
Doctoral research assistant

*ETH Zurich*
Institute of Technology in Architecture
Block Research Group - BRG
Stefano-Franscini-Platz 1, HIB E 44
8093 Zurich, Switzerland

*http://block.erch.ethz.ch <http://block.erch.ethz.ch>*
calvo@arch.ethz.ch
