### ISSUE TITLE
Unnecessary plots on Horizontal Equilibrium and Plots of Form-Force

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_tna#20]
# Feature Request

I would suggest that we take out the unnecessary plots on the iterations for functions "horizontal" and "horizontal_nodal".

Also, I miss the nice plots of form and force that were able before on the package so we can easily visualise equilibrium.

Thanks.

**Comment by ricardoavelino** [comment]
Also @brgcode I suggest adding a during iterations plot (maybe a gif, or just a delayed plot with the iterations)... in which we can see the dual graph moving to become parallel with the form diagram.

**Comment by tkmmark** [comment]
Sort of like this?
![image](https://user-images.githubusercontent.com/9421670/76871697-aa873b00-686b-11ea-8547-fa17ebd6e43b.png)

**Comment by tkmmark** [comment]
I also miss this dual form/force plot.

**Comment by brgcode** [comment]
could you split this into two requests?part 1 is already solved...

**Comment by juney-lee** [comment]
This has been resolved with force diagram conduit in RV2.
