### ISSUE TITLE
More transparent way to add feet

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_tna#21]
# Feature Request

It would be useful to have a more transparent way to add the feets to both cases:

1) Close network (contain the edges in the boundaries), should receive information of which node add the feet to.

2) Open network (containing leaves), should automatically consider the feets as the leaves unless explicitly said so....

     2.1) User should be able to input an open network by considering still a "closed network" in which the edges in the boundary become 'is_edge': False

3) Option to do it manually... Which parameters have to be set to achieve a sort of 'is_feet': True

**Comment by juney-lee** [comment]
Feet is no longer used in the generation of the form diagram.
