### ISSUE TITLE
Iteration still printing in horizontal equilibrium when using horizontal_nodal

### ISSUE THREAD

**Issue by ricardoavelino** [BlockResearchGroup/compas_tna#22]
Hello, 

The display for print the number of iterations was solver for the horizontal equilibrium, but not when using the horizontal_nodal solver. 

This calls for the function parallelise_nodal that has no attribute 'display'. Can we either comment it out or add attribute 'display' to this function? 

https://github.com/BlockResearchGroup/compas_tna/blob/a8008c724ce4b324520da4082730e9839d5a8f57/src/compas_tna/utilities/diagrams.py#L87

Gracias!
Ricardo

**Comment by brgcode** [comment]
something must have gone wrong with pushing and pulling on my end because this was fixed a few days ago. now also in the online repo :)
