### ISSUE TITLE
cast values as floats before reattributing them to form

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#24]
please check all equilibration methods involving numpy
as an example:

![image](https://user-images.githubusercontent.com/9421670/93273008-144eb600-f7b7-11ea-9918-f94d4babe0f7.png)

this is to ensure that attributes are not np.float64 but float
so that the form diagrams can be json-serialisable, and therefore makes it possible for form diagrams to be saved.........................................................................................

**Comment by brgcode** [comment]
this is unnecessary

```python
>>> from numpy import float64
>>> from compas.datastructures import Mesh
>>> import compas
>>> mesh = Mesh.from_obj(compas.get('faces.obj'))
>>> mesh.vertex_attribute(mesh.get_any_vertex(), 'x', float64(1))
>>> mesh.to_json('test.json')
>>> 
```

**Comment by tkmmark** [comment]
It is true that the use of numpy floats per se does not create any issue now.
But it can easily lead to downstream complications when one is then working with the stored attributes, such as with logical operators, since not all numpy datatypes with python analogues can be serialised...
![image](https://user-images.githubusercontent.com/9421670/95127509-5e90da80-0758-11eb-9594-355d79471b1d.png)

**Comment by brgcode** [comment]
again, unnecessary...
```python
>>> from numpy import bool_
>>> from compas.datastructures import Mesh
>>> import compas
>>> mesh = Mesh.from_obj(compas.get('faces.obj'))
>>> mesh.vertex_attribute(0, 'x', bool_(1))
>>> type(mesh.vertex_attribute(0, 'x'))
<class 'numpy.bool_'>
>>> mesh.to_json('test.json')
>>>
```

**Comment by tkmmark** [comment]
Ah, you mean Gonzalo added the functionality in the Sep 21 merge.  I see now, thanks.
