### ISSUE TITLE
feetless 2.0 issues: compatibility with pre-gs-ified form diagram

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#25]
(1) It would be great to have boundaries identification methods for FormDiagrams with GS-induced elements that (as an option) can identify the boundaries associated with the pre-GSified-mesh (in other words, the option to find the boundaries of form diagrams whereby the unloaded faces lining the unsupported edges,  feets once upon a time, and any other non-physical elements to be introduced in future compas_tna are removed).

(2) Ditto for metrics like number_of_x() that can discount the non-physical GS-induced elements (e.g. edges that are not edges) 

(3) On a related note, it would be great to have methods that can easily revert a form diagram to its pre-GSified mesh.

**Comment by juney-lee** [comment]
@tkmmark I think these issues have been resolved by now?

**Comment by juney-lee** [comment]
I believe 1) and 2) have been resolved. 3) will be possible with a new scene management based on compas_ui.
