### ISSUE TITLE
feetless 2.0 issues: option to turn off auto-removal of corners and disabling of edges in update_boundaries

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#26]
While author understands the reasoning behind this, the auto-removal and -disabling can cause disruptions... (for instance, users may use corners as key markers/datums, etc....)

**Comment by juney-lee** [comment]
Not sure if it is worth having a special override for the corner edges of a quad mesh though. Seems like this particular situation is quite specific to your problem, so maybe you could find a temporary work-around for this?

@brgcode thoughts?

**Comment by juney-lee** [comment]
I believe this has been discussed and either addressed or removed from consideration.

Disabling of auto-removal of anchored corners (whose neighbors are also anchors) would result in unnecessary edges in the force diagram whose length will be 0 anyway. Workaround would be to leave them as free vertices, then change the 'is_anchor' attribute to True once the formdiagram has been created.
