### ISSUE TITLE
_edges in horizontal_nodal_numpy needs to be expressed in _vertex indices...

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#27]
Because the latest exciting revision of TNA only draws the interior vertices of the FormDiagrams as faces in the ForceDiagram, and therefore include only the spaces surrounding these nodes as vertices in the ForceDiagram... and because ForceDiagram's keys are drawn directly from FormDiagram's keys... the mapping between vertex key and index in the ForceDiagram is more necessary than ever.

Consider inserting:
_edges = [[_k_i[u], _k_i[v]] for u, v in _edges]

As is already the case in horizontal_numpy...

**Comment by tkmmark** [comment]
@brgcode

**Comment by brgcode** [comment]
that is indeed an oversight, probably because `horizontal_nodal_numpy` is a bit deprecated in favour of `horizontal_nodal` and received less attention recently. i will add the indexing...

**Comment by brgcode** [comment]
should be fixed. please check and close if solved...

**Comment by juney-lee** [comment]
@tkmmark has this been resolved?

**Comment by tkmmark** [comment]
Yes, resolved by Tom I believe. Thanks
