### ISSUE TITLE
spelling consistency: parallelise -> parallelize

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#28]
Because of the awful, but ultimately reasonable decision made here:

https://github.com/compas-dev/compas/issues/127

**Comment by tkmmark** [comment]
methods in question:
    'parallelise',
    'parallelise_sparse',
    'parallelise_nodal',

**Comment by juney-lee** [comment]
This should be updated (will "-ize" everywhere across other GS packages as well). @tkmmark could you submit a pull request for this?
