### ISSUE TITLE
example files no longer working

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#3]
Revisiting TNA this month because I am attempting to wrap some of the core features in Grasshopper for our workshop.  However, I noticed that the example files are no longer working.  The viewers are gone and the vertical equilibrium methods are also having issues.

**Comment by brgcode** [comment]
will take care of that today...

**Comment by tkmmark** [comment]
Thanks; actually I was looking at the AAG examples and those reflect the new TNA structure; they work.
So my question now is mostly about which viewer to use.

**Comment by brgcode** [comment]
there is no viewer for TNA anymore, so I would just use Rhino...

**Comment by brgcode** [comment]
is this resolved? can i close it?
