### ISSUE TITLE
Last working version of non-Matrix based formulation of horizontal nodal

### ISSUE THREAD

**Issue by tkmmark** [BlockResearchGroup/compas_tna#4]
Do we still have the non-elegant non-array/matrix non-Num/Scipy loopy version of horizontal modal somewhere? This will remove one xfunc call in the Grasshopper wrapper and save a couple of seconds per solve.

**Comment by brgcode** [comment]
not sure, but it would be a good idea to not use XFunc at all and use the newer RPC functionality...

**Comment by brgcode** [comment]
`compas.rpc` is the improved version of `XFunc`. should be available in the latest version of the framework...

**Comment by brgcode** [comment]
RPC stands for "Remote Procedure Calls"

**Comment by tkmmark** [comment]
@GeneKao 
Gene also mentioned this today.
But he also doesn't know how it is implemented.
Is there an example that we can look at?

**Comment by brgcode** [comment]
all of compas_tna has been rewritten to use RPC. therefore, there should be plenty of examples available...
