### ISSUE TITLE
count_dof - no attribute 'xyz' in form

### ISSUE THREAD

**Issue by kiunana** [BlockResearchGroup/compas_tna#8]
When trying to count the dof, gets the following error

File "C:\compas_tna\src\compas_tna\utilities\diagrams.py", line 55, in count_dof
    xyz   = form.xyz()
AttributeError: 'FormDiagram' object has no attribute 'xyz'

**Comment by brgcode** [comment]
`count_dof` and `identify_dof` are recent additions and were not meant to be part of the public API yet. sorry about that!

will finalise the implementation and re-release as soon as possible...

**Comment by brgcode** [comment]
this should be fixed now. please let me know if it is not.

note however, that these functions only provide meaningful results in a "bestfit" context, and that the current implementation is just there for illustrative purposes. a more robust version will be made available through `compas_ags`...
